nav:
  # Navigation bar logo image
  logo: /img/favicon.ico
  display_title: true
  display_post_title: true
  # Whether to fix navigation bar
  fixed: true

menu:
  首页: / || fas fa-home
  废话本: /shuoshuo/ || fas fa-podcast
  分类: /catagories/ || fas fa-theater-masks
  小游戏||fas fa-solid fa-gamepad||hide:
    2048: /games/2048/ || fa-solid fa-cubes
    像素农场: /games/pixel-farm/ || fa-solid fa-wheat-awn
  关于作者: /about/ || fas fa-snowman

code_blocks:
  # Code block theme: darker / pale night / light / ocean / false
  theme: darker
  macStyle: false
  # Code block height limit (unit: px)
  height_limit: false
  word_wrap: false

  # Toolbar
  copy: true
  language: true
  # true: shrink the code blocks | false: expand the code blocks | none: expand code blocks and hide the button
  shrink: false
  fullpage: false

# Social media links
# Formal:
#   icon: link || the description || color
social: 
  fab fa-github: https://github.com/yujingyao-dev || Github || '#D32F2F'
  fas fa-envelope: mailto:yujingyao3751314@gmail.com || Email || '#D32F2F'
  fab fa-youtube: https://space.bilibili.com/544308446 || Bilibili || '#D32F2F'
  fa-brands fa-x-twitter: https://x.com/YuJingyao2007 || X || '#D32F2F'

favicon: /img/favicon.ico

avatar:
  img: /img/avatar.png
  effect: false

# --------------------------------------
# Aside Settings
# --------------------------------------

aside:
  enable: true
  hide: false
  # Show the button to hide the aside in bottom right button
  button: true
  mobile: true
  # Position: left / right
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: INTP | 新加坡留子
    button:
      enable: false
      icon: fab fa-github
      text: 前往我的Github账号
      link: https://github.com/yujingyao-dev
  card_announcement:
    enable: false
    content: 
  card_recent_post:
    enable: true
    # If set 0 will show all
    limit: 5
    # Sort: date / updated
    sort: date
    sort_order:
  card_newest_comments:
    enable: true
    sort_order:
    limit: 6
    # Unit: mins, save data to localStorage
    storage: 10
    avatar: true
  card_categories:
    enable: false
    # If set 0 will show all
    limit: 8
    # Choose: none / true / false
    expand: none
    sort_order:
  card_tags:
    enable: true
    # If set 0 will show all
    limit: 40
    color: false
    # Order of tags, random/name/length
    orderby: random
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: 1
    sort_order:
  card_archives:
    enable: false
    # Type: monthly / yearly
    type: monthly
    # Eg: YYYY年MM月
    format: MMMM YYYY
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
    # If set 0 will show all
    limit: 8
    sort_order:
  card_post_series:
    enable: true
    # The title shows the series name
    series_title: false
    # Order by title or date
    orderBy: 'date'
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    # Time difference between publish date and now
    # Formal: Month/Day/Year Time or Year/Month/Day Time
    # Leave it empty if you don't enable this feature
    runtime_date:

# About the per_page
# if you set it to true, it will load mathjax/katex script in each page
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' or 'katex: true' in page's front-matter)
math:
  # Choose: mathjax, katex
  # Leave it empty if you don't need math
  use: mathjax
  per_page: true
  hide_scrollbar: false

  mathjax:
    # Enable the contextual menu
    enableMenu: true
    # Choose: all / ams / none, This controls whether equations are numbered and how
    tags: none

  katex:
    # Enable the copy KaTeX formula
    copy_tex: false

theme_color:
  enable: true
  main: "#D32F2F"
  paginator: "#5D0E1A"
  text_selection: "#F44336"
  link_color: 
  meta_color: "#757575"
  hr_color: "#424242"
  code_foreground: "#F5F5F5"
  code_background: "rgba(33, 33, 33, 0.9)" # 接近纯黑
  # 目录高亮
  toc_color: "#D32F2F"
  # 引用左边竖线
  blockquote_padding_color: "#D32F2F"
  # 引用背景：非常淡的黑色
  blockquote_background_color: "rgba(66, 66, 66, 0.3)"
  # 滚动条
  scrollbar_color: "#FFB74D"

  meta_theme_color_light: "#F5F5F5"
  meta_theme_color_dark: "#121212"


comments:
  # Up to two comments system, the first will be shown as default
  # Leave it empty if you don't need comments
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42/Artalk
  # Format of two comments system : Disqus,Waline
  use: Twikoo
  # Display the comment name next to the button
  text: true
  # Lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: false
  # Display comment count in post's top_img
  count: false
  # Display comment count in Home Page
  card_post_count: false


# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://blog-comments-six-roan.vercel.app
  region:
  # Use Twikoo visitor count as the page view count
  visitor: true
  option:


# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
inject:
  head:
  bottom:

subtitle:
  enable: true
  # Typewriter Effect
  effect: true
  # Customize typed.js
  # https://github.com/mattboldt/typed.js/#customization
  typed_option:
  # Source - Call the third-party service API (Chinese only)
  # It will show the source first, then show the content of sub
  # Choose: false/1/2/3
  # false - disable the function
  # 1 - hitokoto.cn
  # 2 - https://api.aa1.cn/doc/yiyan.html
  # 3 - jinrishici.com
  source: false
  # If you close the typewriter effect, the subtitle will only show the first line of sub
  sub: 
    - Ad astra abyssosque.
    - 愿此行，终抵群星！
    
default_top_img: 'linear-gradient(20deg, #5d0e1a, #d32f2f, #f44336, #ffb74d)'

photofigcaption: true

index_post_content:
  method: 2
  # If you set method to 2 or 3, the length need to config
  length: 500

footer_img: 'linear-gradient(120deg, #5d0e1a, #d32f2f, #f44336, #ffb74d)'

wordcount:
  enable: true
  # Display the word count of the article in post meta
  post_wordcount: true
  # Display the time to read the article in post meta
  min2read: true
  # Display the total word count of the website in aside's webinfo
  total_wordcount: true

# Busuanzi count for PV / UV in site
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

mermaid:
  enable: true
  # Write Mermaid diagrams using code blocks
  code_write: true
  # built-in themes: default / forest / dark / neutral
  theme:
    light: default
    dark: dark